apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sou-autores-app-autoscaler
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sou-autores-app
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75
